### ISSUE TITLE
Floating mobs

### ISSUE THREAD

**Issue by KimmoKM** [ccshiro/cc-buglist#1814]
The closed issue #431 still appears to be there and as it has not been reopened, I'm making a new one. [This video](https://www.youtube.com/watch?v=e9gG2Do7mzY) showcases the problem and as suggested in the closed issue, it does seem to be related to mobs slowing down (due to slow effects or them starting to flee). This can happen for anyone with fleeing mobs, but as you can see from the video, an application of frost bolt slow seems to make that particular mob "jump" almost consistently, and the jump might happen even when the mob is standing still casting spells (as seen in the second clip).

For whatever reason, I feel the issue is more common when indoors and it definitely seems to be related to their changes in speed, but I'm fairly sure I've seen mobs left floating as they died even if they didn't try to flee. In addition, while it's quite common, it doesn't seem to happen every time so there appears to be factors other than speed change in play.

**Comment by ccshiro** [comment]
I think it should be fixed now. Will move this to needs testing though (note that it'll take a few hours for the change to be on the test server).

**Comment by KimmoKM** [comment]
Based on my experience, casting frost bolt on mobs was pretty much a reliable way to reproduce this behaviour. I tried it for a while (including clearing out the troll cave the original video was taken from) and it happened less frequently (that's my impression, anyway, I haven't kept original recordings so I can't count). Anyhow, the issue is still present and it's worth noting that, like I already mentioned, it does seem to be far more common indoors, or at least in caves. However, I recorded the event once from outdoors (last clip in [this video](https://www.youtube.com/watch?v=Ke59bW7cq4U&feature=youtu.be)) and in that instance it didn't involve a slow either.

Fleeing/low-health mobs jumping/dying in air is still as common as ever, however. Aside from ones seen in the previous video already, [here's](https://youtu.be/xLca6f5gv3o) some other instances I happened to record today. As you can see from the first clip, it can occur on mobs that don't flee (wasn't the best angle to show it, I admit, but the mob does raise up at around 20% health, I had trouble finding a good clip from my recordings), but it's easily reproduced with mobs that do, like those Frostmane Trolls or Dragonmaw shamans.

In addition, I noticed mobs sometimes "skipping", a behaviour I haven't noticed previously so I thought it might be related to the attempted fix and decided to post about here rather than making a new issue. [Here's](https://www.youtube.com/watch?v=RyVfez14chE&feature=youtu.be) a video that displays a couple of times it occurs. Interestingly, I didn't notice anything like this while testing Eversong Woods quest with my warlock or when killing the frost trolls inside the cave while I gathered this footage in 5 minutes. I've got no clue why that might be (I'd understand cave environment making it a jump, but why didn't I notice this with the lock?)

**Comment by KimmoKM** [comment]
I returned to the Frostmane Hold with my low-level mage, a setup that used to be reliable in reproducing the issue in the past. I dinged twice during the test so it must have been 90+ mobs and I didn't encounter the previous issue once the way it used to present itself (no mobs jumping at frost bolt impact, no floating corpses). There was two [oddities](https://www.youtube.com/watch?v=D0Rof20K3_Y&feature=youtu.be) I encountered, however. First was a jumping mob (sorry about slideshow in the first clip, I must have fucked up recording somehow) seen in the first two clips. However, it happened both times and looked nothing like the issue reported here and instead is probably related to #1679 #1716 #1759. The third clip, however, displays a possible remnant of this issue, mobs turning for a brief instant. This occurred a couple of times.
